export const data = {
  Headphones: [
    {
      id: "1",
      name: "Sony WH-1000XM5",
      brand: "Sony",
      price: "₹29,990",
      img: "/productsImg/earbuds/SonyHeadphone1.png",
      category: "Headphones",
      description:
        "Premium wireless headphones with world-class noise cancellation and exceptional comfort.",
      features: ["ANC", "30 Hours Battery", "Bluetooth 5.2", "Adaptive Sound"],
      rating: 4.8,
      reviews: 5300,
      colors: ["Black", "Silver"],
      option: "Adaptive ANC + Transparency Mode",
      specialProperties: [
        "Sony Integrated Processor V1",
        "Precise Voice Pickup Technology",
        "Lightweight Carbon Fiber Arms",
        "Auto NC Optimization",
      ],
    },
    {
      id: "2",
      name: "Bose QuietComfort 45",
      brand: "Bose",
      price: "₹32,900",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Headphones",
      description:
        "Comfort-focused ANC headphones with smooth balanced sound and all-day comfort.",
      features: ["ANC", "24 Hours Battery", "Lightweight Design"],
      rating: 4.6,
      reviews: 2890,
      colors: ["Black", "White"],
      option: "Quiet Mode + Aware Mode",
      specialProperties: [
        "TriPort Acoustic Architecture",
        "Active EQ Tuning",
        "Soft Protein Leather Cushioning",
      ],
    },
    {
      id: "3",
      name: "Sennheiser Momentum 4 Wireless",
      brand: "Sennheiser",
      price: "₹34,990",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Headphones",
      description:
        "High-resolution audio with powerful bass and an incredible 60-hour battery.",
      features: ["60 Hours Battery", "ANC", "Smart Control App"],
      rating: 4.7,
      reviews: 1842,
      colors: ["Black"],
      option: "Adaptive Noise Cancelling",
      specialProperties: [
        "42mm Dynamic Drivers",
        "Audiophile Sound Signature",
        "Beamforming Mic Array",
      ],
    },
    {
      id: "4",
      name: "JBL Tour One M3",
      brand: "JBL",
      price: "₹24,999",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Headphones",
      description:
        "Punchy bass, immersive sound, and True Adaptive Noise Cancellation.",
      features: ["Adaptive ANC", "50 Hours Battery", "Hi-Res Audio"],
      rating: 4.5,
      reviews: 910,
      colors: ["Black"],
      option: "True Adaptive Noise Cancelling",
      specialProperties: [
        "JBL Pro Sound Drivers",
        "Smart Ambient Awareness",
        "Hi-Res Certified Audio",
      ],
    },
    {
      id: "5",
      name: "Beats Studio Pro",
      brand: "Beats",
      price: "₹27,999",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Headphones",
      description:
        "Stylish premium headphones with Spatial Audio and powerful bass.",
      features: ["ANC", "Spatial Audio", "USB-C Audio"],
      rating: 4.4,
      reviews: 1500,
      colors: ["Black", "Navy", "Brown"],
      option: "ANC + Personalized Spatial Audio",
      specialProperties: [
        "Custom Beats Chip",
        "Dual-Mode USB-C Audio",
        "Real-Time Adaptive EQ",
      ],
    },
    {
      id: "6",
      name: "Audio-Technica ATH-M50xBT2",
      brand: "Audio-Technica",
      price: "₹21,999",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Headphones",
      description:
        "Studio-grade audio tuned for accuracy with wireless freedom.",
      features: ["40 Hours Battery", "Studio Sound", "Low Latency"],
      rating: 4.6,
      reviews: 2400,
      colors: ["Black", "Blue"],
      option: "Studio Monitor Accuracy Mode",
      specialProperties: [
        "45mm Large-Aperture Drivers",
        "Dual Microphone Beamforming",
        "Low-Latency Wireless Mode",
      ],
    },
    {
      id: "7",
      name: "Skullcandy Crusher Evo",
      brand: "Skullcandy",
      price: "₹14,999",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Headphones",
      description:
        "Bass-heavy wireless headphones with adjustable haptic feedback.",
      features: ["Haptic Bass", "Rapid Charge", "Bluetooth 5.0"],
      rating: 4.4,
      reviews: 1900,
      colors: ["Grey", "Black"],
      option: "Adjustable Haptic Bass Slider",
      specialProperties: [
        "Crusher Sensory Bass Technology",
        "Personal Sound by Audiodo",
        "Rapid Charging Capability",
      ],
    },
    {
      id: "8",
      name: "Marshall Monitor II ANC",
      brand: "Marshall",
      price: "₹29,999",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Headphones",
      description:
        "Classic Marshall design with rich sound, warm bass, and great ANC.",
      features: ["ANC", "30 Hours Battery", "Iconic Design"],
      rating: 4.7,
      reviews: 1200,
      colors: ["Black"],
      option: "Multi-Step Active Noise Cancellation",
      specialProperties: [
        "Custom Marshall Drivers",
        "Classic Vinyl Leather Build",
        "Multi-Directional Control Knob",
      ],
    },
  ],

  Earbuds: [
    {
      id: "1",
      name: "Sony WF-1000XM5",
      brand: "Sony",
      price: "₹24,990",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Earbuds",
      description:
        "Industry-leading ANC earbuds with superb sound and clear call quality.",
      features: ["ANC", "360 Reality Audio", "8+24 Hours Battery"],
      rating: 4.8,
      reviews: 3420,
      colors: ["Black", "Silver"],
      option: "Adaptive ANC + Ambient Mode",
      specialProperties: [
        "Dynamic Driver X",
        "AI Voice Isolation",
        "Bone Conduction Sensor",
      ],
    },
    {
      id: "2",
      name: "Bose QuietComfort Ultra Earbuds",
      brand: "Bose",
      price: "₹27,900",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Earbuds",
      description:
        "Flagship ANC earbuds with immersive spatial audio and premium comfort.",
      features: ["Immersive Audio", "ANC", "IPX4"],
      rating: 4.7,
      reviews: 1800,
      colors: ["White", "Black"],
      option: "Immersive Audio + Aware Mode",
      specialProperties: [
        "Bose CustomTune Technology",
        "ActiveSense Adjustment",
        "Adaptive Mic Array",
      ],
    },
    {
      id: "3",
      name: "Sennheiser Momentum True Wireless 4",
      brand: "Sennheiser",
      price: "₹29,990",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Earbuds",
      description:
        "Audiophile-grade TWS with rich sound and strong bass performance.",
      features: ["ANC", "High-Res Audio", "28 Hours Battery"],
      rating: 4.6,
      reviews: 1400,
      colors: ["Black", "White"],
      option: "High-Resolution ANC Mode",
      specialProperties: [
        "TrueResponse Transducers",
        "AptX Lossless Audio",
        "WindSafe Beamforming Mics",
      ],
    },
    {
      id: "4",
      name: "JBL Tour Pro 2",
      brand: "JBL",
      price: "₹19,999",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Earbuds",
      description:
        "Smart-case earbuds with ANC and customizable sound via JBL app.",
      features: ["Smart Touch Case", "ANC", "Bluetooth 5.3"],
      rating: 4.5,
      reviews: 900,
      colors: ["Black", "Beige"],
      option: "Smart Case + Adaptive ANC",
      specialProperties: [
        "Touchscreen Charging Case",
        "JBL Signature Pro Sound",
        "Ambient Aware Technology",
      ],
    },
    {
      id: "5",
      name: "Beats Fit Pro",
      brand: "Beats",
      price: "₹18,999",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Earbuds",
      description:
        "Workout-focused earbuds with secure fit and Spatial Audio support.",
      features: ["ANC", "Spatial Audio", "Apple H1 Chip"],
      rating: 4.6,
      reviews: 1600,
      colors: ["Black", "Pink", "White"],
      option: "Secure Fit Wing Design + ANC",
      specialProperties: [
        "Apple H1 Chip",
        "Adaptive EQ",
        "Dynamic Head Tracking",
      ],
    },
    {
      id: "6",
      name: "Nothing Ear (2)",
      brand: "Nothing",
      price: "₹11,999",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Earbuds",
      description:
        "Transparent design earbuds with balanced sound and strong ANC.",
      features: ["ANC", "Dual Chamber Drivers", "Hi-Res Audio"],
      rating: 4.4,
      reviews: 2100,
      colors: ["Transparent White", "Transparent Black"],
      option: "Personal Sound Profile + ANC",
      specialProperties: [
        "Transparent Design",
        "Dual Chamber Drivers",
        "High-Res LHDC 5.0",
      ],
    },
    {
      id: "7",
      name: "OnePlus Buds Pro 2",
      brand: "OnePlus",
      price: "₹11,999",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Earbuds",
      description:
        "Premium earbuds with dual drivers and fast pair features.",
      features: ["ANC", "Dual Drivers", "Dolby Atmos"],
      rating: 4.5,
      reviews: 3100,
      colors: ["Black", "Green"],
      option: "Dual Driver Sound + ANC",
      specialProperties: [
        "MelodyBoost Dual Drivers",
        "Dynaudio Tuning",
        "Low-Latency Link",
      ],
    },
    {
      id: "8",
      name: "Samsung Galaxy Buds2 Pro",
      brand: "Samsung",
      price: "₹17,999",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Earbuds",
      description:
        "Comfortable and lightweight earbuds with Hi-Fi sound quality.",
      features: ["24-bit Hi-Fi Audio", "ANC", "IPX7"],
      rating: 4.6,
      reviews: 3900,
      colors: ["Graphite", "White", "Purple"],
      option: "24-bit Hi-Fi Audio + ANC",
      specialProperties: [
        "Samsung Seamless Codec (SSC HiFi)",
        "Intelligent Voice Detect",
        "360° Audio with Head Tracking",
      ],
    },
  ],

  Speakers: [
    {
      id: "1",
      name: "JBL Charge 5",
      brand: "JBL",
      price: "₹14,999",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Speakers",
      description:
        "Rugged portable speaker with powerful bass and long battery life.",
      features: ["IP67", "20 Hours Battery", "Powerbank Feature"],
      rating: 4.6,
      reviews: 5400,
      colors: ["Black", "Blue", "Red"],
      option: "Portable Powerbank Speaker",
      specialProperties: [
        "JBL Original Pro Sound",
        "Dual Bass Radiators",
        "PartyBoost Pairing",
      ],
    },
    {
      id: "2",
      name: "Sony SRS-XE300",
      brand: "Sony",
      price: "₹19,990",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Speakers",
      description:
        "Wide sound field speaker ideal for outdoor and party use.",
      features: ["IP67", "Live Sound Mode", "Up to 24 Hours Battery"],
      rating: 4.5,
      reviews: 2200,
      colors: ["Black", "Grey"],
      option: "Wide Sound Dispersion Mode",
      specialProperties: [
        "X-Balanced Speaker Unit",
        "Line-Shape Diffuser",
        "Dual Passive Radiators",
      ],
    },
    {
      id: "3",
      name: "Bose SoundLink Flex",
      brand: "Bose",
      price: "₹15,900",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Speakers",
      description:
        "Portable speaker with PositionIQ technology for adaptive sound.",
      features: ["PositionIQ", "IP67", "12 Hours Battery"],
      rating: 4.7,
      reviews: 3100,
      colors: ["Black", "White", "Blue"],
      option: "Auto Sound Calibration",
      specialProperties: [
        "PositionIQ Adaptive Tuning",
        "Waterproof & Dustproof Build",
        "Optimized Transducer",
      ],
    },
    {
      id: "4",
      name: "Marshall Emberton II",
      brand: "Marshall",
      price: "₹17,999",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Speakers",
      description:
        "Iconic Marshall design with rich, loud, and immersive sound.",
      features: ["IP67", "30 Hours Battery", "Stack Mode"],
      rating: 4.8,
      reviews: 2500,
      colors: ["Black", "Cream"],
      option: "True Stereophonic Sound Mode",
      specialProperties: [
        "Multi-Directional Audio",
        "Classic Marshall Build",
        "Bluetooth 5.1 Enhanced Range",
      ],
    },
    {
      id: "5",
      name: "Ultimate Ears Boom 3",
      brand: "Ultimate Ears",
      price: "₹12,999",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Speakers",
      description:
        "360-degree sound speaker with excellent durability.",
      features: ["360° Audio", "IP67", "15 Hours Battery"],
      rating: 4.5,
      reviews: 2800,
      colors: ["Blue", "Black"],
      option: "360° Immersive Sound Mode",
      specialProperties: [
        "Magic Button Controls",
        "Floatable Waterproof Body",
        "Deep Bass Radiator",
      ],
    },
    {
      id: "6",
      name: "Anker Soundcore Motion+",
      brand: "Anker",
      price: "₹9,999",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Speakers",
      description:
        "Affordable Hi-Res speaker with deep bass and extended treble.",
      features: ["Hi-Res Audio", "Bluetooth 5.0", "12 Hours Battery"],
      rating: 4.6,
      reviews: 4100,
      colors: ["Black", "Blue"],
      option: "Hi-Res Audio Boost Mode",
      specialProperties: [
        "Ultra-Wide Frequency Range",
        "Titanium Drivers",
        "BassUp™ Technology",
      ],
    },
    {
      id: "7",
      name: "Sonos Roam",
      brand: "Sonos",
      price: "₹19,999",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Speakers",
      description:
        "Premium smart speaker with Wi-Fi + Bluetooth and adaptive tuning.",
      features: ["Auto Trueplay", "IP67", "Wi-Fi + Bluetooth"],
      rating: 4.4,
      reviews: 1600,
      colors: ["Black", "White"],
      option: "Auto Trueplay Adaptive Tuning",
      specialProperties: [
        "Dual Driver Setup",
        "Wi-Fi Multiroom Support",
        "Smart Assistant Integration",
      ],
    },
    {
      id: "8",
      name: "Tribit StormBox Blast",
      brand: "Tribit",
      price: "₹16,999",
      img: "/productsImg/earbuds/SonyHeadphone.png",
      category: "Speakers",
      description:
        "Powerful party speaker with deep bass and multicolor lighting.",
      features: ["Light Show", "30 Hours Battery", "IPX7"],
      rating: 4.6,
      reviews: 2900,
      colors: ["Black"],
      option: "Dynamic Party Light Mode",
      specialProperties: [
        "XBass Boost",
        "RGB Party Lights",
        "Dual Woofer + Tweeter Setup",
      ],
    },
  ],
};

export type CategoryType = keyof typeof data;
